name: Build Greenshot

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore Greenshot.sln

      - name: Build solution
        run: msbuild Greenshot.sln /p:Configuration=Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Greenshot-Executable
          path: bin\Release\
